# GoReleaser configuration for toki
# Note: Due to CGO requirements for SQLite, this config builds for the current platform only
# Multi-platform releases require running goreleaser on each platform (handled by CI matrix)
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: toki
    binary: toki
    main: ./cmd/toki
    env:
      - CGO_ENABLED=1
    # Due to CGO requirements, builds must be done natively on each platform
    # Use --single-target flag to build only for current platform
    # CI workflow runs on both macOS and Linux to create all binaries
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    tags:
      - sqlite_omit_load_extension

archives:
  - id: toki
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Other'
      order: 999

brews:
  - repository:
      owner: harper
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/harper/toki
    description: "A super simple git-aware todo manager"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "toki"
    test: |
      system "#{bin}/toki", "version"
